name: VZ Premium Scraper
on:
  repository_dispatch:
    types: [scrape-request]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - run: npm install
      
      - name: Scrape VZ Article
        run: |
          node -e "
          const { scrapeVZArticle } = require('./scraper.js');
          const axios = require('axios');
          
          (async () => {
            try {
              const articleText = await scrapeVZArticle(
                '${{ github.event.client_payload.url }}',
                '${{ secrets.VZ_EMAIL }}',
                '${{ secrets.VZ_PASSWORD }}'
              );
              
              await axios.post('${{ github.event.client_payload.webhook }}', {
                url: '${{ github.event.client_payload.url }}',
                title: '${{ github.event.client_payload.title }}',
                pubDate: '${{ github.event.client_payload.pubDate }}',
                content: articleText,
                trending_topics: '${{ github.event.client_payload.trending_topics }}'
              });
              console.log('Success!');
            } catch (error) {
              console.error('Scraping failed:', error);
            }
          })();
          "
