- name: Scrape VZ Article
  run: |
    node -e "
    const { scrapeVZArticle } = require('./scraper.js');
    const payload = ${{ toJson(github.event.client_payload) }};
    
    scrapeVZArticle(payload.url, '${{ secrets.VZ_EMAIL }}', '${{ secrets.VZ_PASSWORD }}')
      .then(text => {
        fetch(payload.webhook, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ 
            url: payload.url,
            title: payload.title,
            pubDate: payload.pubDate,
            trending_topics: payload.trending_topics,
            text: text,
            success: true 
          })
        });
      })
      .catch(err => {
        fetch(payload.webhook, {
          method: 'POST', 
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ 
            url: payload.url,
            error: err.message,
            success: false 
          })
        });
      });
    "
